name: Go Validate

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.x'

      - run: go mod tidy
      - run: go fmt ./...

      - name: Verify no changes from go fmt and go mod tidy
        run: |
          echo "==> Checking if any change in the codebase..."
          git diff --exit-code; if [ $$? -eq 1 ]; then \
          echo "Changes found in the repository"; \
          echo "Please fix the errors and resubmit."; \
          exit 1; \
          fi
